spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://52.15.95.130:3306/master?serverTimezone=UTC&characterEncoding=UTF-8
    username: SB
    password: 1234
  jpa:
    database: MYSQL
    open-in-view: false
    show-sql: true # true 설정시 JPA 쿼리문 확인 가능
    hibernate:
      generate-ddl: true
      ddl-auto: update # DDL(create, alter, drop) 정의시 DB의 고유 기능을 사용할 수 있다.
    properties:
      hibernate:
        format_sql: true #JPA의 구현체인 Hibernate가 동작하면서 발생한 SQL의 가독성을 높여준다.




